### ISSUE TITLE
Eko-lan / HA integration

### ISSUE THREAD

**Issue by mlaciak** [aelias-eu/hewalex-geco-protocol#5]
Hi, is there a way to integrate it with eko-lan (G927) and take the payload from there in home assistant?
I've tried to run the script and connect to eko-lan by changing the values of ip/port in
`serial.serial_for_url('socket://ip:port')`
unfortunately- no luck.
Do i need to have separate device (rs485 -> lan) to make it work or eko-lan module should be enough?

**Comment by aelias-eu** [comment]
Hi, 
i don't think, that you can use the G927 with code in this repository. AFAIK, the G927 is connecting to the hewalex cloud. 
You need a simple RS485/USB or RS485/LAN converter for our code & for direct communication.

**Comment by mlaciak** [comment]
Thanks, a lot for Your replay :)
I will try to get some converter and test that, if you have any that you can recommend please let me know.
